### ISSUE TITLE
German characters are not displayed correctly

### ISSUE THREAD

**Issue by DominikSchaller** [djfun/jamulus-os-scripts#4]
![Jamulus-Stick-Bug](https://user-images.githubusercontent.com/60886607/104321049-64c6ed80-54e3-11eb-8b3f-97e20a64f19a.jpg)

**Comment by djfun** [comment]
@DominikSchaller mit welchem Programm hast du das Image auf den USB-Stick geschrieben?

**Comment by DominikSchaller** [comment]
> @DominikSchaller mit welchem Programm hast du das Image auf den USB-Stick geschrieben?

Rufus. Ich habe es zuerst mit Win32 Disk Imager probiert (Empfehlung von Dieter), damit konnte ich aber gar nicht booten.

**Comment by DominikSchaller** [comment]
> > @DominikSchaller mit welchem Programm hast du das Image auf den USB-Stick geschrieben?
> 
> Rufus

Ich habe es zuerst mit Win32 Disk Imager probiert (Empfehlung von Dieter), damit konnte ich aber gar nicht booten.

**Comment by djfun** [comment]
ok, das "Problem" mit win32 disk imager könnte an #3 liegen, das habe ich lokal bei mir schon eingebaut, wartet nur noch auf Veröffentlichung.
Ob dann auch die Probleme mit Rufus behoben werden, teste ich nach Feierabend.

**Comment by djfun** [comment]
Falls du die Gelegenheit hast, nochmal zu testen: https://djfun.de/jamulus-os-easy-de-prototype-0.2.iso
Dieses neue Image sollte nun auch im UEFI-Modus starten, wenn es von win32 disk imager geschrieben wird. Außerdem habe ich für den UEFI-Modus locale=de_DE gesetzt, womit auch hier die Umlaute als UTF-8 richtig erkannt werden sollten.

**Comment by DominikSchaller** [comment]
Danke, ich werde es erst im Laufe der Woche testen können!

Ich hab noch zwei Fragen, wenn wir uns eh schon unterhalten:
1. Ist die Performance besser, wenn ich Linux fest installiere? Oder nutzt Linux die Laptop-Hardware auch optimal aus, wenn ich von USB starte?
2. Auf dem Boot-Stick kann ich nichts persistieren, richtig? Oder werden Einstellungen z.B. in Jamulus, heruntergeladene Dateien etc. gespeichert?

**Comment by djfun** [comment]
zu 1. der größte Performance-Unterschied wird im Lesen und Schreiben von Daten sein. Festplatte oder SSD sind im allgemeinen schneller als der Zugriff über USB. Wenn das System aber mal läuft, dann findet das meiste eh im Arbeitsspeicher statt, wo du dann vermutlich keine Unterschiede feststellen wirst. tldr: System bootet schneller bei fester Installation, für Jamulus und Jack ist es egal.
zu 2. wenn Platz auf dem USB-Datenträger vorhanden ist, legt das System automatisch eine persistente Partition an. wo dann Einstellungen und Änderungen gespeichert werden.
Es kann sein, dass das in deiner aktuellen Version noch nicht für UEFI-Boot funktioniert, in der neuen Version, die ich oben verlinkt habe, sollte das aber gehen. Das führt natürlich auch zu einer verstärkten Abnutzung des USB-Sticks (das haben Flash-Speicher so an sich), solange das System nicht 24/7 im Einsatz ist, nehmen wir das in Kauf.

**Comment by DominikSchaller** [comment]
Hey Martin, das Problem mit der falschen Zeichendarstellung ist in der neuen Version (heute heruntergeladen) immer noch da.

**Comment by DominikSchaller** [comment]
Der Fehler mit der falschen Darstellung ist in der neuen Version 0.3 behoben.
