### ISSUE TITLE
Warning when using Rufus

### ISSUE THREAD

**Issue by DominikSchaller** [djfun/jamulus-os-scripts#6]
![Rufus Bug](https://user-images.githubusercontent.com/60886607/104974651-f14c4100-59f8-11eb-88f7-438639129dd4.jpg)

**Comment by djfun** [comment]
Hi Dominik,

this is perfectly normal message when using Rufus, see https://github.com/pbatard/rufus/wiki/Security#Download_of_SyslinuxGRUB_resources

Just for reference: are you using ISO or DD mode?

**Comment by DominikSchaller** [comment]
I am using ISO. But the screenshot is not from me, but from a guy from my chorus. He asked me if this is normal and what to do. But if it cannot be changed, so be it.
