### ISSUE TITLE
“Clean Desktop”

### ISSUE THREAD

**Issue by WardinT** [djfun/jamulus-os-scripts#8]
Nicht für die Kernfunktionalität erforderliche Icons und Links sollen in einem Ordner ("Mehr..." o.ä.) verborgen werden.

**Comment by djfun** [comment]
alle normalen desktop-Files der ursprünglichen JamulusOS-Version wurden bereits nach ~/Erweitert verschoben. Dieser Issue betrifft Icons, die zusätzlich zum Inhalt des Desktop-Ordners angezeigt werden, wie z.B. mountbare Partitionen.

**Comment by djfun** [comment]
Fixed by 95002a547f5e377435866748ed023cb814f514fa and the desktop configuration in d8c9df4846ddcc621e6402a921d325ef6859a525

The ubiquity (Installer) icon will be moved to ~/Erweitert on first boot, the other icons are hidden. All partitions can still be accessed by using the file manager.
